exports.filmes = function(ocorrencias){
    pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Filmes</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-blue">
              <h1>Filmes</h1>
            </header>
            
            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <th>Identificador</th>
                        <th>Título</th>
                        <th>Ano</th>
                        <th>Elenco</th>
                        <th>Géneros</th>
                      </tr>
    `
    ocorrencias.forEach( ocorr => {
        pagHTML += `
        <tr>
            <td>${ocorr.idFilme}</td>
            <td>${ocorr.title}</td>
            <td>${ocorr.year}</td>
            <td>${ocorr.cast}</td>
            <td>${ocorr.genres}</td>
        </tr>
        `
    });
    pagHTML += `
    </table>
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by EngWeb2024</h5>
            </footer>
            
        </div>
    </body>
</html>
    `
    return pagHTML
}

exports.generos = function(ocorrencias){
    pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Géneros</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-blue">
              <h1>Géneros</h1>
            </header>
            
            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <th>Identificador</th>
                        <th>Género</th>
                      </tr>
    `
    ocorrencias.forEach( ocorr => {
        pagHTML += `
        <tr>
            <td>${ocorr.idGen}</td>
            <td>${ocorr.genero}</td>
        </tr>
        `
    });
    pagHTML += `
    </table>
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by EngWeb2024</h5>
            </footer>
            
        </div>
    </body>
</html>
    `
    return pagHTML
}

exports.atores = function(ocorrencias){
    pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Atores</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-blue">
              <h1>Atores</h1>
            </header>
            
            <div class="w3-container">
                <table class="w3-table w3-striped">
                    <tr>
                        <th>Identificador</th>
                        <th>Nome</th>
                        <th>Filmes</th>
                        <th>Elenco</th>
                        <th>Géneros</th>
                      </tr>
    `
    ocorrencias.forEach( ocorr => {
        pagHTML += `
        <tr>
            <td>${ocorr.idAtor}</td>
            <td>${ocorr.nome}</td>
            <td>${ocorr.filmes}</td>
        </tr>
        `
    });
    pagHTML += `
    </table>
            </div>
            
            <footer class="w3-container w3-blue">
              <h5>Generated by EngWeb2024</h5>
            </footer>
            
        </div>
    </body>
</html>
    `
    return pagHTML
}

exports.filme = function(filme){
    var castList = filme[0].cast.join(', ');
    var genresList = filme[0].genres.join(', ');
    var pagHTML = `
    <html>
    <head>
        <title>Filme: ${filme[0].title}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Filme ${filme[0].title}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Identificador: </b> ${filme[0].idFilme}</li>
                    <li><b>Título: </b> ${filme[0].title}</li>
                    <li><b>Ano: </b> ${filme[0].year}</li>
                    <li><b>Elenco: </b> ${castList}</li>
                    <li><b>Generos: </b> ${genresList}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `

    

    pagHTML +=     `</ul></div>
            <footer class="w3-container w3-teal">
                <address>EngWeb2024 - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}