// Lista de Compositores
exports.compositoresListPage = function(compositores, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores</h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>dataNasc</th><th>dataObito</th><th>Período</th>
                        </tr>
                `
        for(let i=0; i < compositores.length ; i++){
        pagHTML += `
                <tr>
                    <td>${compositores[i].id}</td>
                    <td>
                        <a href="/compositores/${compositores[i].id}">
                            ${compositores[i].nome}
                        </a>
                    </td>
                    <td>${compositores[i].dataNasc}</td>
                    <td>${compositores[i].dataObito}</td>
                    <td>${compositores[i].periodo}</td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Guilherme Oliveira in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// Página de um Compositor
exports.compositorPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Período: </b> ${compositor.periodo}</li>
                    <li><b>Biografia: </b> ${compositor.bio}</li>


                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `
            
    

    pagHTML +=     `</ul></div>
            <footer class="w3-container w3-teal">
                <address>EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// Lista de Periodos
exports.periodosListPage = function(periodos, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Periodos</h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Período</th>
                        </tr>
                `
        for(let i=0; i < periodos.length ; i++){
        pagHTML += `
                <tr>
                    <td>${periodos[i].id}</td>
                    <td>
                        <a href="/periodos/${periodos[i].id}">
                            ${periodos[i].periodo}
                        </a>
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Guilherme Oliveira in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// Página de um período
exports.periodoPage = function( periodo, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Período: ${periodo.periodo}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Período ${periodo.periodo}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Período: </b> ${periodo.periodo}</li>
                    <li><b>ID: </b> ${periodo.periodo}</li>
                    <li><b>Compositores: </b></li>
            `;
            console.log(periodo.compositores)
            for(let i=0; i < periodo.compositores.length; i++){
                key = periodo.compositores[i]
                    pagHTML += `
                        <li>${key}</li>
                    `
                
            };
        
    

    pagHTML += `
        </ul>
        </div>
            <footer class="w3-container w3-teal">
                <address>EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}